2024-05-06 16:34:19,710 INFO    MainThread:79301 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-05-06 16:34:19,710 INFO    MainThread:79301 [wandb_setup.py:_flush():76] Configure stats pid to 79301
2024-05-06 16:34:19,710 INFO    MainThread:79301 [wandb_setup.py:_flush():76] Loading settings from /home/leverimmy/.config/wandb/settings
2024-05-06 16:34:19,710 INFO    MainThread:79301 [wandb_setup.py:_flush():76] Loading settings from /home/leverimmy/documents/Introduction-to-Artificial-Intelligence/Classification/src/wandb/settings
2024-05-06 16:34:19,710 INFO    MainThread:79301 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-06 16:34:19,710 INFO    MainThread:79301 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-06 16:34:19,710 INFO    MainThread:79301 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'Classification/src/main.py', 'program_abspath': '/home/leverimmy/documents/Introduction-to-Artificial-Intelligence/Classification/src/main.py', 'program': '/home/leverimmy/documents/Introduction-to-Artificial-Intelligence/Classification/src/main.py'}
2024-05-06 16:34:19,711 INFO    MainThread:79301 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-06 16:34:19,711 INFO    MainThread:79301 [wandb_init.py:_log_setup():521] Logging user logs to /home/leverimmy/documents/Introduction-to-Artificial-Intelligence/Classification/src/wandb/run-20240506_163419-x5ghybtp/logs/debug.log
2024-05-06 16:34:19,711 INFO    MainThread:79301 [wandb_init.py:_log_setup():522] Logging internal logs to /home/leverimmy/documents/Introduction-to-Artificial-Intelligence/Classification/src/wandb/run-20240506_163419-x5ghybtp/logs/debug-internal.log
2024-05-06 16:34:19,711 INFO    MainThread:79301 [wandb_init.py:init():561] calling init triggers
2024-05-06 16:34:19,711 INFO    MainThread:79301 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-05-06 16:34:19,711 INFO    MainThread:79301 [wandb_init.py:init():611] starting backend
2024-05-06 16:34:19,711 INFO    MainThread:79301 [wandb_init.py:init():615] setting up manager
2024-05-06 16:34:19,719 INFO    MainThread:79301 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-06 16:34:19,721 INFO    MainThread:79301 [wandb_init.py:init():623] backend started and connected
2024-05-06 16:34:19,730 INFO    MainThread:79301 [wandb_init.py:init():715] updated telemetry
2024-05-06 16:34:19,737 INFO    MainThread:79301 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-05-06 16:35:49,767 ERROR   MainThread:79301 [wandb_init.py:init():774] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-06 16:35:49,785 ERROR   MainThread:79301 [wandb_init.py:init():1199] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/leverimmy/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/leverimmy/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-06 16:35:50,792 WARNING MsgRouterThr:79301 [router.py:message_loop():77] message_loop has been closed
